### ISSUE TITLE
receiver启动后没有图像显示




### ISSUE THREAD

**Issue by frienkie** [AreteQin/compressed-video-transport#1]
前提：
在树莓派和电脑上按照turtlebot3教程配置，测试usb_cam的image_raw在rqt内正常观察，键盘控制移动正常。
使用
pip install opencv-python-headless
在树莓派和电脑安装opencv
树莓派clone和make后，运行
rosrun compressed-video-transport publisher
电脑运行
rosrun compressed-video-transport receiver _image_transport:=compressed

无error警告
通过rqt观察到topic名为color的image，延迟很高

**Comment by AreteQin** [comment]
rqt_graph 我看一下

**Comment by frienkie** [comment]
> rqt_graph 我看一下



![image](https://github.com/AreteQin/compressed-video-transport/assets/55905272/c32c5aa9-8eed-4357-9c21-7404810fb4e8)
![image](https://github.com/AreteQin/compressed-video-transport/assets/55905272/5840c69d-5928-461a-909e-0b4e2ae6fccc)

**Comment by frienkie** [comment]
找到原因了
树莓派没有安装image-transport-plugins所致
`sudo apt-get install -y ros-noetic-image-transport-plugins`
安装后一切正常
